name: 'Release Schedule'
inputs:
  rotation:
    required: true
  github-token:
    required: true
runs:
  using: 'composite'
  steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install packages for github-script
        run: npm i date-fns
      - name: Create Release Issue
        uses: actions/github-script@v6
        env:
          ROTATION: ${{ inputs.rotation }}
        with:
          github-token: ${{ inputs.github-token }}
          script: |
            const startOfWeek = require('date-fns/startOfWeek');
            const nextFriday = require('date-fns/nextFriday');
            const format = require('date-fns/format');
            const eachDayOfInterval = require('date-fns/eachDayOfInterval');
            
            const today = new Date();
            const start = startOfWeek(today, { weekStartsOn: 1 });
            const end = nextFriday(start);
            const { ROTATION } = process.env;
            const rotation = ROTATION.split('\n').map((item) => item.trim());
            let assignee = rotation[0];
            
            core.info(`Rotation: ${rotation.join(', ')}`);
            
            const ISSUE_TITLE = 'Release Tracking'
            
            const iterator = github.paginate.iterator(
              github.rest.issues.listForRepo,
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open',
                per_page: 100,
              }
            );
            
            let currentReleaseIssue = null;
            
            for await (const page of iterator) {
              currentReleaseIssue = page.data.find((issue) => {
                return issue.title === ISSUE_TITLE;
              });
              
              if (currentReleaseIssue) {
                break;
              }
            }
            
            const ISSUE_BODY = [
              `_This is a scheduled issue for tracking the release between ${format(start, 'EEEE do')} and ${format(end, 'EEEE do')}_`,
              '',
            ];
            
            if (currentReleaseIssue) {
              const assignees = currentReleaseIssue.assignees.map((assignee) => {
                return `@${assignee.login}`;
              });

              ISSUE_BODY.push('| Last week | Value |');
              ISSUE_BODY.push('| :-- | :-- |');
              ISSUE_BODY.push(`| Issue | [${currentReleaseIssue.title}](${currentReleaseIssue.html_url}) |`);
              ISSUE_BODY.push(`| Conductor(s) | ${assignees.join(' ')} |`);

              github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: currentReleaseIssue.number,
                state: 'closed',
                state_reason: 'completed',
              });
              
              if (currentReleaseIssue.assignees.length > 0) {
                const currentAssignee = currentReleaseIssue.assignees[0].login;
                if (rotation.includes(currentAssignee)) {
                  assignee = rotation[(rotation.indexOf(currentAssignee) + 1) % rotation.length];
                }
              }
            }
            
            ISSUE_BODY.push('## Timeline');
            ISSUE_BODY.push('<!-- Provide updates for release activities, like cutting releases and different integration points -->');
            ISSUE_BODY.push('');
            
            for (const day of eachDayOfInterval({ start, end })) {
              ISSUE_BODY.push(`- ${format(day, 'EEEE do')}`);
            }
            
            ISSUE_BODY.push('');

            ISSUE_BODY.push('## Checklist');
            ISSUE_BODY.push('');
            ISSUE_BODY.push('- [ ] Prerelease available on npm');
            ISSUE_BODY.push('- [ ] Integration checks passed');
            ISSUE_BODY.push('- [ ] Release available on npm');
            ISSUE_BODY.push('- [ ] Dependencies have been updated to latest');
            
            core.info(`Assignee: ${assignee}`);
            
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: ISSUE_TITLE,
              body: ISSUE_BODY.join('\n'),
              assignees: assignee ? [assignee] : [],
            });
